apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot
spec:
  project: development
  source:
    repoURL: https://github.com/rcabezas29/iot-cicd.git
    targetRevision: HEAD
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true