apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rcabezas29/app-iot.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true