apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2

---
apiVersion: v1
kind: Pod
metadata:
  name: app1

---
apiVersion: v1
kind: Pod
metadata:
  name: app3
