Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
		vb.cpus = 4
	end

	config.vm.define "rcabezas" do |rcabezas_config|
		rcabezas_config.vm.hostname = "rcabezasS"
		rcabezas_config.vm.network "private_network", ip: "192.168.56.110"
		
		rcabezas_config.vm.provision "shell", inline: <<-SHELL
			sudo bash /vagrant/scripts/deploy.sh
			ip link add eth1 type dummy && ip addr add 192.168.56.110/24 dev eth1 && ip link set eth1 up
		SHELL
	end
end
