Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
		vb.cpus = 4
	end

	config.vm.define "rcabezas" do |rcabezas_config|
		rcabezas_config.vm.hostname = "rcabezasS"
		rcabezas_config.vm.network "private_network", ip: "192.168.56.110"
		
		rcabezas_config.vm.provision "shell", inline: <<-SHELL
			sudo bash /vagrant/scripts/deploy.sh
		SHELL
	end
end
