apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: app-one
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-one
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app-one
    http:
      paths:
        - path: /app1.com
          pathType: Prefix
          backend:
            service:
              name: app-one
              port:
                number: 80


---


apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: app-two
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-two
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app-two
    http:
      paths:
        - path: /app2.com
          pathType: Prefix
          backend:
            service:
              name: app-two
              port:
                number: 80


---


apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: app-three
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-three
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app-three
    http:
      paths:
        - path: /app3.com
          pathType: Prefix
          backend:
            service:
              name: app-three
              port:
                number: 80
