Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.synced_folder "config/", "/config", create: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "rcabezasS" do |rcabezas_config|
    rcabezas_config.vm.hostname = "rcabezasS"
    rcabezas_config.vm.network "private_network", ip: "192.168.56.110"
    
    rcabezas_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl net-tools

      mkdir -p /etc/rancher/k3s && cp /config/master.yaml /etc/rancher/k3s/config.yaml
      curl -sfL https://get.k3s.io | sh -s - server
      ip link add eth1 type dummy && ip addr add 192.168.56.110/24 dev eth1 && ip link set eth1 up
    SHELL
  end

  config.vm.define "alvrodriSW" do |alvrodri_config|
    alvrodri_config.vm.hostname = "alvrodriSW"
    alvrodri_config.vm.network "private_network", ip: "192.168.56.111"

    alvrodri_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl net-tools

      mkdir -p /etc/rancher/k3s && cp /config/slave.yaml /etc/rancher/k3s/config.yaml
      curl -sfL https://get.k3s.io | sh -s - agent
      ip link add eth1 type dummy && ip addr add 192.168.56.111/24 dev eth1 && ip link set eth1 up
    SHELL
  end

end
