Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "rcabezas" do |rcabezas_config|
    rcabezas_config.vm.hostname = "rcabezasS"
    rcabezas_config.vm.network "private_network", ip: "192.168.56.110"
    
    rcabezas_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  config.vm.define "alvrodri" do |alvrodri_config|
    alvrodri_config.vm.hostname = "alvrodriSW"
    alvrodri_config.vm.network "private_network", ip: "192.168.56.111"

    alvrodri_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | K3S_URL='https://192.168.56.110:6443' K3S_TOKEN='K10ea8c798713420c0a870de9823ef5f08b45db9b8ac4dea4614166d9eeb1fce4f8::server:18eaad6aa9ea1590f014307cb5b88f10' sh -
    SHELL
  end

end
