Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "rcabezas" do |rcabezas_config|
    rcabezas_config.vm.hostname = "rcabezasS"
    rcabezas_config.vm.network "private_network", ip: "192.168.56.110"
    
    rcabezas_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
      curl -sfL https://get.k3s.io | sh -
      cat /var/lib/rancher/k3s/server/token > /shared/token
    SHELL
  end

  config.vm.define "alvrodri" do |alvrodri_config|
    alvrodri_config.vm.hostname = "alvrodriSW"
    alvrodri_config.vm.network "private_network", ip: "192.168.56.111"

    alvrodri_config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl

      export K3S_URL='https://192.168.56.110'
      export K3S_TOKEN=$(cat /shared/token)

      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

end
