Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
    end
  
    config.vm.define "ubuntu" do |ubuntu_config|
      ubuntu_config.vm.hostname = "ubuntu"
      
      ubuntu_config.vm.network "private_network", ip: "192.168.56.97"
      ubuntu_config.vm.network "forwarded_port", guest: 8081, host: 8081
      ubuntu_config.vm.network "forwarded_port", guest: 8082, host: 8082

      ubuntu_config.vm.provision "shell", path: "scripts/install.sh"
      ubuntu_config.vm.provision "shell", path: "scripts/init.sh"
    end
  end